"""add saved_opportunities table

Revision ID: 63bbbf65874e
Revises: 24bb22c52dba
Create Date: 2026-05-22 00:53:11.255776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63bbbf65874e'
down_revision: Union[str, None] = '24bb22c52dba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_opportunities',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'opportunity_id', name='uq_saved_user_opp')
    )
    op.create_index(op.f('ix_saved_opportunities_id'), 'saved_opportunities', ['id'], unique=False)
    op.create_index(op.f('ix_saved_opportunities_user_id'), 'saved_opportunities', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_opportunities_user_id'), table_name='saved_opportunities')
    op.drop_index(op.f('ix_saved_opportunities_id'), table_name='saved_opportunities')
    op.drop_table('saved_opportunities')
    # ### end Alembic commands ###
