# app/models/application.py
# Application — a student applying to an opportunity

from sqlalchemy import Column, String, Text, Integer, DateTime, ForeignKey
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import relationship
from app.models.base import TimeStampedModel


class Application(TimeStampedModel):
    __tablename__ = "applications"

    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False, index=True)
    opportunity_id = Column(UUID(as_uuid=True), ForeignKey("opportunities.id"), nullable=False, index=True)

    # Status lifecycle: draft → submitted → accepted/rejected
    status = Column(String, default="draft", nullable=False)

    # AI-generated fields
    prep_score = Column(Integer, nullable=True)      # Preparation score 0-100
    missing_items = Column(JSONB, default=list)      # What's missing from the profile
    generated_letter = Column(Text, nullable=True)   # Letter generated by Gemini

    # Personal notes
    notes = Column(Text, nullable=True)

    # When the student actually submitted
    applied_at = Column(DateTime, nullable=True)

    # Relationships
    user = relationship("User", back_populates="applications")
    opportunity = relationship("Opportunity", back_populates="applications")

    def __repr__(self):
        return f"<Application user={self.user_id} opp={self.opportunity_id} status={self.status}>"